name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Dockerhub
        env: 
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/p2p-backend:latest -f Dockerfile .

      - name: Push to Dockerhub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/p2p-backend:latest

  deploy-backend:
    runs-on: self-hosted
    needs: build-and-push-backend

    steps:
      - name: Create certs directory
        run: sudo mkdir -p /home/runner/certs

      - name: Decode and save certificate to runner folder
        env:
          PFX_CERTIFICATE_BASE64: ${{ secrets.BACKEND_CERTIFICATE }}
        run: echo "$PFX_CERTIFICATE_BASE64" | base64 --decode > /home/runner/certs/certificate.pfx

      - name: Save certificate password to runner folder
        env:
          PFX_CERTIFICATE_PASSWORD: ${{ secrets.BACKEND_CERTIFICATE_PASSWORD }}
        run: echo "$PFX_CERTIFICATE_PASSWORD" > /home/runner/certs/certificate_password.txt

      - name: Pull the Docker image
        run: sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/p2p-backend:latest

      - name: Stop and remove old container
        run: sudo docker rm -f p2p-backend-container || true

      - name: Run Docker container with mounted certificates
        run: |
          sudo docker run -d --restart always \
          -p 20169:20169 \
          -v /home/runner/certs:/usr/src/app/certs \
          --name p2p-backend-container ${{ secrets.DOCKERHUB_USERNAME }}/p2p-backend:latest

      - name: Prune old Docker images
        run: sudo docker image prune -f

  deploy-frontend:
    runs-on: ubuntu-latest
    needs: build-and-push-backend
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./Frontend
